### ISSUE TITLE
pycuda 2017.1.1 not installable, so cuvarbase won't install

### ISSUE THREAD

**Issue by paulkerry1** [johnh2o2/cuvarbase#2]
Hi
I'm trying to install cuvarbase under debian 10 amd64 which uses python 3.7.3.
"pip3 install cuvarbase" fails as pycuda 2017.1.1 will not install. I've also tried building pycuda-2017.1.1 from source using the instructions on https://johnh2o2.github.io/cuvarbase/install.html and that also fails.
The same failure is described on...
https://github.com/inducer/pycuda/issues/184
and was fixed with pycuda release 2018.1.1

I can install pycuda 2019.1.2 perfectly fine using pip, but then cannot install cuvarbase either from pip or the git version as it's specifically looking for pycuda==2017.1.1

Is there a way to use cuvarbase with pycuda 2019.1.2 ?

Regards
Paul.

**Comment by astrobatty** [comment]
I pulled a request to solve this issue. Here: https://github.com/johnh2o2/cuvarbase/pull/3.

I don't know if it will be ever accepted, but if you clone cuvarbase, than you can change in line 47 `'pycuda==2017.1.1'` to `'pycuda>=2017.1.1'` in setup.py. After this, `pip install .` can install cuvarbase using the newest pycuda.

**Comment by johnh2o2** [comment]
Thanks to both of you for your help here. I've updated the master branch and (as of now) the pypi version to require only `pycuda>=2017.1.1` instead of `pycude==2017.1.1` (via @astrobatty 's PR). However, there are some newly introduced bugs when using the latest PyCUDA version (as found by another user, particularly when using batched Lomb-Scargle), and since I no longer have access to my own CUDA-compatible GPU machine, it's quite difficult for me to debug.

If either of you know anyone with GPU experience interested in contributing to this package, please let me know! They would be most welcome, as I am no longer in the astronomy field and while I may make occasional contributions here this is mostly experimental code.

**Comment by astrobatty** [comment]
@johnh2o2 Maybe forcing pycuda to be <2020.1?

**Comment by johnh2o2** [comment]
> @johnh2o2 Maybe forcing pycuda to be <2020.1?

I worry that will cause problems in the future, but maybe this will be necessary...

I'm going to close this issue but if anyone has any issues installing/using/testing cuvarbase related to pycuda/cuda versions, please post a new issue!
