### ISSUE TITLE
PDM: Binless functions are not callable

### ISSUE THREAD

**Issue by astrobatty** [johnh2o2/cuvarbase#8]
From the 4 available kernels, ``binless_tophat`` and ``binless_gauss`` cannot be used. The following error is raised:

![image](https://user-images.githubusercontent.com/45241990/112629964-43fd0b80-8e35-11eb-97e8-9571bdc8213e.png)

The problem is caused by the fact that we you compile these functions [here](https://github.com/johnh2o2/cuvarbase/blob/9cb76d1c4d0458327dd6f988cbbed2e8244ece9b/cuvarbase/pdm.py#L138), you except names without ``nbins`` suffix (which should really be the case), but after that when the function is selected [here](https://github.com/johnh2o2/cuvarbase/blob/9cb76d1c4d0458327dd6f988cbbed2e8244ece9b/cuvarbase/pdm.py#L182), the ``nbins`` suffix is required regardless the type of the function.
This can solved by providing a bin size even if the kernel in the ``.cu`` file won't use it.

**Comment by johnh2o2** [comment]
Hey @astrobatty -- thanks for all of your interest and contributions to this package! Yes PDM was an early feature that was more or less abandoned as the code developed since I never had much use for PDM in my own personal research. I will try to fix this bug when I have some time, but there are several other issues that are more pressing (though this particular issue seems hopefully like it shouldn't take too long) -- if you want to make a PR I would be happy to look it over and merge if it looks ok. I should have some time in the coming weeks to devote to a couple of longstanding cuvarbase bugs, so hopefully I can get this addressed.

Posts like this are very helpful, so please feel free to make posts for any other problems you encounter :)

**Comment by astrobatty** [comment]
This shouldn't take too much time to be solved. I will take a look at it.
